### ISSUE TITLE
Windows fails to install because EVN variables do not exist

### ISSUE THREAD

**Issue by jamime** [dhoer/chef-java_se#18]
By default we use the check on [line 2](https://github.com/dhoer/chef-java_se/blob/6d3070b8046601c6a1087b516a587b4aa43f6568/recipes/_windows_install.rb#L2).
However, there are cases when neither of these variables exist.

I recently encountered this on the modern.ie win7 ie11 vagrant box when attempting to install selenium.
I suggest falling back to `ENV['ProgramFiles']` when the previous values do not exist.

**Comment by dhoer** [comment]
Sounds good. Can you please submit a PR?

**Comment by dhoer** [comment]
Would replacing ENV['ProgramW6432'] with ENV['ProgramFiles'] be the best approach?

**Comment by jamime** [comment]
I don't know enough ruby to add appropriate tests.
There is actually a few cases to cater for http://stackoverflow.com/a/11211727

`program_files = node['java_se']['arch'] == 'x64' ? ENV['ProgramW6432'] : ENV['ProgramFiles']` should do the trick.

On a 64 bit system `ProgramW6432` will always point to `C:/Program Files` and on a 32 bit system `ProgramFiles` will always point to `C:/Program Files`. 

_Note: Although we are targeting the same directory `ProgramFiles` won't always point to  `C:/Program Files` on 64 bit systems hence the need for `ProgramW6432`._

**Comment by dhoer** [comment]
This breaks the install...

**Comment by dhoer** [comment]
I had to test for env variable:
https://github.com/dhoer/chef-java_se/blob/master/libraries/default.rb#L76-L82

See if this works for you.

**Comment by dhoer** [comment]
Waiting for a thumbs up or down on this. If all is good, then I will release it.

**Comment by dhoer** [comment]
I went ahead and released.  Please reopen if you are still having issues.
