### ISSUE TITLE
Running CookStyle produced 15 errors

### ISSUE THREAD

**Issue by dburns-vistra** [dhoer/chef-java_se#24]
I have 15 errors when running cookstyle.

Inspecting 15 files
......WW.C..CCC

Offenses:

libraries/default.rb:18:3: C: Use cmd.exitstatus == 0 instead of cmd.exitstatus.zero?.
  cmd.exitstatus.zero?
  ^^^^^^^^^^^^^^^^^^^^
libraries/default.rb:29:1: W: Unnecessary disabling of Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/MethodLength, Metrics/PerceivedComplexity.
# rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/MethodLength, Metrics/PerceivedComplexity
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/downloader.rb:99:7: W: Unnecessary disabling of Metrics/MethodLength.
      # rubocop:disable Metrics/MethodLength
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/downloader.rb:101:74: C: Use limit == 0 instead of limit.zero?.
        raise ArgumentError, "too many download failures from #{url}" if limit.zero?
                                                                         ^^^^^^^^^^^
recipes/_linux_install.rb:68:61: C: Use extract.exitstatus == 0 instead of extract.exitstatus.zero?.
    raise("Failed to extract file #{tarball_name}!") unless extract.exitstatus.zero?
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:72:12: C: Use move.exitstatus == 0 instead of move.exitstatus.zero?.
    unless move.exitstatus.zero?
           ^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:122:38: C: Use same_prio.exitstatus == 0 instead of same_prio.exitstatus.zero?.
      alternative_exists_same_prio = same_prio.exitstatus.zero?
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:125:28: C: Use alt_exists.exitstatus == 0 instead of alt_exists.exitstatus.zero?.
      alternative_exists = alt_exists.exitstatus.zero?
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:132:16: C: Use remove_alt.exitstatus == 0 instead of remove_alt.exitstatus.zero?.
        unless remove_alt.exitstatus.zero?
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:144:16: C: Use install_alt.exitstatus == 0 instead of install_alt.exitstatus.zero?.
        unless install_alt.exitstatus.zero?
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:155:16: C: Use set_alt.exitstatus == 0 instead of set_alt.exitstatus.zero?.
        unless set_alt.exitstatus.zero?
               ^^^^^^^^^^^^^^^^^^^^^^^^
recipes/_linux_install.rb:159:18: C: Use set_alt.exitstatus == 0 instead of set_alt.exitstatus.zero?.
          unless set_alt.exitstatus.zero?
                 ^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:1:1: C: Carriage return character detected.
require 'chefspec' ...
^^^^^^^^^^^^^^^^^^
spec/unit/recipes/default_spec.rb:1:1: C: Carriage return character detected.
# ...
^
test/smoke/default/default_test.rb:1:1: C: Carriage return character detected.
# # encoding: utf-8 ...
^^^^^^^^^^^^^^^^^^^

15 files inspected, 15 offenses detected

C:\Users\xxxx\chef-repo\cookbooks\java_se>

**Comment by dhoer** [comment]
I don't use CookStyle, but would accept a PR that includes it.

**Comment by dhoer** [comment]
The April 18 release will contain cookstyle.

**Comment by dhoer** [comment]
Did the latest release fix this?

**Comment by dburns-vistra** [comment]
I haven’t tried to use or test this yet since I sent you the pull request that you looked at and responded to.


Daniel R. Burns |Tools Infrastructure Architect – Automation & Cloud Platform Services |[cid:image001.png@01D2B9C8.228D5090] | EP 26-050F | Phone: 214-812-2277<tel:+1(214)812-2277>|Mobile: 469-298-8917<tel:+1(469)298-8917>|Email: daniel.burns@vistraenergy.com<mailto:daniel.burns@vistraenergy.com>
