### ISSUE TITLE
JDK Download does not work anymore

### ISSUE THREAD

**Issue by philipthomasme** [dhoer/chef-java_se#27]
The JDK download does not work anymore.
The direct download in the browser only works after accepting the license prior to same and the generated download link contains some kind of hash that is part of the new download URL.
So it seems as if Oracle implemented a cookie gate and a new download path.

**Comment by dylan-colaco** [comment]
What version of java se cookbook are you using?

**Comment by philipthomasme** [comment]
8.112.0
