### ISSUE TITLE
Add support for JCE

### ISSUE THREAD

**Issue by vrivellino** [dhoer/chef-java_se#31]
It'd be great if this cookbook could support installing [Java Cryptography Extension](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) policy files.

**Comment by suthsc** [comment]
JDK 1.8_151 and later has unlimited crypto enabled by default: [JCE Policy Changes](https://bugs.openjdk.java.net/browse/JDK-8170157)

**Comment by dhoer** [comment]
@suthsc long time no see, how are things?

**Comment by dhoer** [comment]
@suthsc I now live in Tucson.  Been here over 3 years now and love it.  Note that this cookbook is up for adoption if you would like to take ownership.

**Comment by vrivellino** [comment]
> JDK 1.8_151 and later has unlimited crypto enabled by default: JCE Policy Changes

Nice, I didn't realize that! Just a FYI for others who may see this, JCE is enabled by default in JDK 1.8_161 and later, and can be validated via:

```
$ jrunscript -e "print (javax.crypto.Cipher.getMaxAllowedKeyLength('AES') >= 256)"
true
$ jrunscript -e "print (javax.crypto.Cipher.getMaxAllowedKeyLength('RC5') >= 256)"
true
```

> Note that this cookbook is up for adoption if you would like to take ownership.

@dhoer: If no one steps up, I'd be willing to take on ownership.

**Comment by dhoer** [comment]
@vrivellino that would be fantastic!  If you could copy this repo and provide me your supermarket userid, I can then update the readme on this repo to point to yours and make you the owner on supermarket.  I can stay on as a collaborator to help support you, if you ever need it.

**Comment by vrivellino** [comment]
@dhoer: Done. New repo is https://github.com/vrivellino/chef-java_se and my supermarket id is: `vrivellino`
