### ISSUE TITLE
Add an option for INSTALLDIRPUBJRE?

### ISSUE THREAD

**Issue by tevert** [dhoer/chef-java_se#5]
http://docs.oracle.com/javase/7/docs/webnotes/install/windows/jdk-installation-windows.html

The "INSTALLDIRPUBJRE" switch allows you to specify the install location of the JRE. This would allow users to install the JDK and JRE side-by-side in a non-default location, instead of having the JRE always end up in program files (on Windows, at least).  

NOTE: Oracle's docs lie a little bit, the value of the switch needs to be quoted in order for it to work, just like INSTALLDIR.

**Comment by dhoer** [comment]
You can change the java_home location:
https://github.com/dhoer/chef-java_se/blob/master/attributes/default.rb#L4

This should then override the default install location:
https://github.com/dhoer/chef-java_se/blob/master/recipes/_windows_install.rb#L4-L9

The jre is added to that location based on PublicjreFeature in win_addlocal attribute:
https://github.com/dhoer/chef-java_se/blob/master/attributes/default.rb#L23

Let me know if this is not working as expected.

**Comment by tevert** [comment]
The install location only covers the location of the JDK. The JRE installs itself as a completely separate entity, to a default location in Program Files. Hence, Oracle providing the additional argument to change its location. 

Note that there *are* two JREs - there's another one that *is* nested within the JDK, but that one is intended for the JDK's use only. It doesn't get put in the windows registry and is technically "hidden". 

Some more info on that here: http://stackoverflow.com/questions/18896541/oracle-jdk-installs-two-jres

**Comment by dhoer** [comment]
Can you please verify that setting java_home e.g. C:\myjava would not result in something like:

C:\myjava\jdk1.7.0_40\jre\bin\java.exe
C:\myjava\jre7\bin\java.exe

for the installation?

**Comment by tevert** [comment]
Yep, for java_home = 'E:\Java\JDK-8.0.60', I get:
E:\Java\JDK-8.0.60\bin\java.exe
C:\Program Files\Java\jre1.8.0_60\bin\java.exe
(and E:\Java\JDK-8.0.60\jre\bin\java.exe)

**Comment by dhoer** [comment]
Thanks, do you want to submit a PR for that as well?

**Comment by tevert** [comment]
I can, it will likely be later this afternoon.

**Comment by dhoer** [comment]
Great, it might require an additional test suite in test kitchen. But if you can test the functionality within the default suite, I would have no problems with that.

**Comment by dhoer** [comment]
Thanks again for the patch. Release 8.60.10 is now out on supermarket.
