### ISSUE TITLE
Add an option for checksums

### ISSUE THREAD

**Issue by tevert** [dhoer/chef-java_se#6]
It would be nice to have a checksum attribute for validating downloads, similar to chef's remote_file and similar resources.

**Comment by dhoer** [comment]
The checksums are there:
https://github.com/dhoer/chef-java_se/blob/master/attributes/bind.rb

Can you please submit a pull request that adds that information to the readme?

Thanks in advance.

**Comment by dhoer** [comment]
Thanks for the PR
