### ISSUE TITLE
sudo is overwritten

### ISSUE THREAD

**Issue by gilhauer** [dhoer/chef-java_se#9]
Hi,

I'm using the java_se cookbook to install a JVM on CentOS 7.0 but it looks like it's somehow clobbering /usr/bin/sudo.

Before I converge with kitchen:
[vagrant@java8-centos-70 ~]$ ls -l /usr/bin/sudo
---s--x--x. 1 root root 130712 Jun 10  2014 /usr/bin/sudo
[vagrant@java8-centos-70 ~]$

After I converge with kitchen:
[vagrant@java8-centos-70 ~]$ ls -l /usr/bin/sudo
---x--x--x. 1 root root 130712 Jun 10  2014 /usr/bin/sudo

I'm using a wrapper cookbook that simply includes the java_se cookbook:

recipes/java.rb:
include_recipe 'java_se'   # https://github.com/agileorbit-cookbooks/java

and my attributes are:
default['java_se']['version'] = '1.8.0_66'
default['java_se']['java_home'] = '/usr/java'

**Comment by dhoer** [comment]
Interesting, what version of chef-client are you using?

**Comment by gilhauer** [comment]
The output is ...

Starting Chef Client, version 12.5.1
       Compiling Cookbooks...
       Recipe: java_se::_download_java
       ....

**Comment by dhoer** [comment]
Side note, the version should not be set.  If I release a new version of Java, it will break your code.  I will update the documentation to note this.

**Comment by gilhauer** [comment]
ok, noted -- how should I set the version then?

**Comment by dhoer** [comment]
In your metadata.rb:
    `depends java_se, '~> 8.0' # to always get the latest version`
or 
    `depends 'java_se', '~> 8.65.0' # to pin to 8.65 version`

**Comment by gilhauer** [comment]
Thanks!

FYI, I made the change (removed the version attribute and using the incantation you recommended) and /usr/bin/sudo is still changing permissions.

**Comment by dhoer** [comment]
I think this is related to Chef and not Java SE cookbook.  I'm going to close this issue.  If you have an example showing that it is related to this cookbook, then please reopen this issue.
